# We are bypassing default_config to prevent the go2rtc crash
frontend:
api:
http:
logger:
  default: info

input_boolean:
  test:
    name: Test Entity
    icon: mdi:test-tube

entity_scheduler:
browser_mod:
recorder:
history:
logbook: